
var hospitaldata = {
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "properties": {
            "ADDRESS": "2033 Main Street",
            "TOWN": "Athol",
            "ZIPCODE": 1331,
            "NAME": "Athol Memorial Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 2,
            "DPHNUMBER": 2226,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 21,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 4,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 25,
            "Percentage_of_Occupancy_Total": 19.2,
            "Average_Daily_Census_Total": 4.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.2084945, 42.5861447]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "211 Park Street",
            "TOWN": "Attleboro",
            "ZIPCODE": 2703,
            "NAME": "Sturdy Memorial Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 129,
            "DPHNUMBER": 2100,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 80,
            "Staffed_Beds_Pediatric": 10,
            "Staffed_Beds_Obstetric": 24,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 14,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 149,
            "Percentage_of_Occupancy_Total": 49.6,
            "Average_Daily_Census_Total": 73.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.2744146, 41.9425151]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "200 Groton Road",
            "TOWN": "Ayer",
            "ZIPCODE": 1432,
            "NAME": "Nashoba Valley Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 52,
            "DPHNUMBER": 2298,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 20,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 26,
            "Percentage_of_Occupancy_Total": 61.1,
            "Average_Daily_Census_Total": 15.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.5732267, 42.5761588]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "44 Binney Street",
            "TOWN": "Boston",
            "ZIPCODE": 2115,
            "NAME": "Dana-Farber Cancer Institute",
            "STATE": "MA",
            "ER_STATUS": "N",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 51,
            "DPHNUMBER": 2335,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Specialty Hospital",
            "Staffed_Beds_MedSurg": 30,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 0,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 30,
            "Percentage_of_Occupancy_Total": 90.9,
            "Average_Daily_Census_Total": 27.3
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.1070649, 42.3374362]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "243 Charles Street",
            "TOWN": "Boston",
            "ZIPCODE": 2114,
            "NAME": "Massachusetts Eye and Ear Infirmary",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 89,
            "DPHNUMBER": 2167,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Specialty Hospital",
            "Staffed_Beds_MedSurg": 22,
            "Staffed_Beds_Pediatric": 19,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 0,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 41,
            "Percentage_of_Occupancy_Total": 35.4,
            "Average_Daily_Census_Total": 14.5
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.0705385, 42.3626938]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "736 Cambridge Street",
            "TOWN": "Boston",
            "ZIPCODE": 2135,
            "NAME": "Caritas St. Elizabeth's Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 126,
            "DPHNUMBER": 2085,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 128,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 18,
            "Staffed_Beds_Psychiatric": 48,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 16,
            "Staffed_Beds_CoronaryICU": 7,
            "Staffed_Beds_NeonatalICU": 18,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 266,
            "Percentage_of_Occupancy_Total": 64.2,
            "Average_Daily_Census_Total": 170.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.1483206, 42.3496483]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "680 Centre Street",
            "TOWN": "Brockton",
            "ZIPCODE": 2302,
            "NAME": "Brockton Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 25,
            "DPHNUMBER": 2118,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 131,
            "Staffed_Beds_Pediatric": 14,
            "Staffed_Beds_Obstetric": 20,
            "Staffed_Beds_Psychiatric": 22,
            "Staffed_Beds_SNF": 29,
            "Staffed_Beds_MedSurgICU": 16,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 251,
            "Percentage_of_Occupancy_Total": 62.4,
            "Average_Daily_Census_Total": 156.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.9907824, 42.0862996]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "330 Mount Auburn Street",
            "TOWN": "Cambridge",
            "ZIPCODE": 2138,
            "NAME": "Mount Auburn Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 100,
            "DPHNUMBER": 2071,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 141,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 23,
            "Staffed_Beds_Psychiatric": 15,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 10,
            "Staffed_Beds_CoronaryICU": 10,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 228,
            "Percentage_of_Occupancy_Total": 65.6,
            "Average_Daily_Census_Total": 149.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.1341297, 42.3748805]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "201 Highland Street",
            "TOWN": "Clinton",
            "ZIPCODE": 1510,
            "NAME": "Clinton Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 132,
            "DPHNUMBER": 2126,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 21,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 0,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 41,
            "Percentage_of_Occupancy_Total": 61.9,
            "Average_Daily_Census_Total": 25.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.6929049, 42.4270581]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "100 Ter Heun Drive",
            "TOWN": "Falmouth",
            "ZIPCODE": 2540,
            "NAME": "Falmouth Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 40,
            "DPHNUMBER": 2289,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 71,
            "Staffed_Beds_Pediatric": 5,
            "Staffed_Beds_Obstetric": 9,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 10,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 103,
            "Percentage_of_Occupancy_Total": 64.5,
            "Average_Daily_Census_Total": 66.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.621994, 41.564121]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "115 Lincoln Street",
            "TOWN": "Framingham",
            "ZIPCODE": 1701,
            "NAME": "MetroWest Medical Center - Framingham Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 49,
            "DPHNUMBER": 2020,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 141,
            "Staffed_Beds_Pediatric": 12,
            "Staffed_Beds_Obstetric": 56,
            "Staffed_Beds_Psychiatric": 34,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 21,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 284,
            "Percentage_of_Occupancy_Total": 53.5,
            "Average_Daily_Census_Total": 151.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.4186859, 42.2847404]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "242 Green Street",
            "TOWN": "Gardner",
            "ZIPCODE": 1440,
            "NAME": "Heywood Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 73,
            "DPHNUMBER": 2036,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 54,
            "Staffed_Beds_Pediatric": 7,
            "Staffed_Beds_Obstetric": 11,
            "Staffed_Beds_Psychiatric": 32,
            "Staffed_Beds_SNF": 19,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 142,
            "Percentage_of_Occupancy_Total": 60.9,
            "Average_Daily_Census_Total": 86.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.986916, 42.587894]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "500 Lynnfield Street",
            "TOWN": "Lynn",
            "ZIPCODE": 1904,
            "NAME": "North Shore Medical Center  - Union Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 3,
            "DPHNUMBER": 2073,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 247,
            "Staffed_Beds_Pediatric": 24,
            "Staffed_Beds_Obstetric": 24,
            "Staffed_Beds_Psychiatric": 64,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 40,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 436,
            "Percentage_of_Occupancy_Total": 59,
            "Average_Daily_Census_Total": 257
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.9792482, 42.5021701]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "170 Governors Avenue",
            "TOWN": "Medford",
            "ZIPCODE": 2155,
            "NAME": "Hallmark Health System - Lawrence Memorial Hospital Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 66,
            "DPHNUMBER": 2038,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 129,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 10,
            "Staffed_Beds_Psychiatric": 52,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 10,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 5,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 216,
            "Percentage_of_Occupancy_Total": 86.8,
            "Average_Daily_Census_Total": 187.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.11026, 42.4256312]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "70 East Street",
            "TOWN": "Methuen",
            "ZIPCODE": 1844,
            "NAME": "Caritas Holy Family Hospital and Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 75,
            "DPHNUMBER": 2225,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 93,
            "Staffed_Beds_Pediatric": 7,
            "Staffed_Beds_Obstetric": 21,
            "Staffed_Beds_Psychiatric": 47,
            "Staffed_Beds_SNF": 16,
            "Staffed_Beds_MedSurgICU": 12,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 229,
            "Percentage_of_Occupancy_Total": 65.8,
            "Average_Daily_Census_Total": 150.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.168304, 42.728462]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "148 Chestnut Street",
            "TOWN": "Needham",
            "ZIPCODE": 2492,
            "NAME": "Beth Israel Deaconess Hospital - Needham",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 53,
            "DPHNUMBER": 2054,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 51,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 7,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 58,
            "Percentage_of_Occupancy_Total": 31.9,
            "Average_Daily_Census_Total": 18.5
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.236694, 42.277256]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "101 Page Street",
            "TOWN": "New Bedford",
            "ZIPCODE": 2740,
            "NAME": "Southcoast Hospitals Group - St. Luke's Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 124,
            "DPHNUMBER": 2010,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 424,
            "Staffed_Beds_Pediatric": 4,
            "Staffed_Beds_Obstetric": 30,
            "Staffed_Beds_Psychiatric": 29,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 40,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 14,
            "Staffed_Beds_Total": 575,
            "Percentage_of_Occupancy_Total": 93.5,
            "Average_Daily_Census_Total": 537.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.938301, 41.626617]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "25 Highland Avenue",
            "TOWN": "Newburyport",
            "ZIPCODE": 1950,
            "NAME": "Anna Jaques Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "N",
            "ORG_ID": 1,
            "DPHNUMBER": 2006,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 68,
            "Staffed_Beds_Pediatric": 3,
            "Staffed_Beds_Obstetric": 12,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 8,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 140,
            "Percentage_of_Occupancy_Total": 62,
            "Average_Daily_Census_Total": 86.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.892113, 42.814262]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "2014 Washington Street",
            "TOWN": "Newton",
            "ZIPCODE": 2462,
            "NAME": "Newton-Wellesley Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 105,
            "DPHNUMBER": 2075,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 114,
            "Staffed_Beds_Pediatric": 12,
            "Staffed_Beds_Obstetric": 36,
            "Staffed_Beds_Psychiatric": 43,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 12,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 272,
            "Percentage_of_Occupancy_Total": 75.6,
            "Average_Daily_Census_Total": 205.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.2478057, 42.3307896]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "30 Locust Street",
            "TOWN": "Northampton",
            "ZIPCODE": 1061,
            "NAME": "Cooley Dickinson Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 50,
            "DPHNUMBER": 2155,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 53,
            "Staffed_Beds_Pediatric": 1,
            "Staffed_Beds_Obstetric": 7,
            "Staffed_Beds_Psychiatric": 18,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 7,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 92,
            "Percentage_of_Occupancy_Total": 93.9,
            "Average_Daily_Census_Total": 86.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.653465, 42.3316486]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "800 Washington Road",
            "TOWN": "Norwood",
            "ZIPCODE": 2062,
            "NAME": "Caritas Norwood Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 41,
            "DPHNUMBER": 2114,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 104,
            "Staffed_Beds_Pediatric": 6,
            "Staffed_Beds_Obstetric": 14,
            "Staffed_Beds_Psychiatric": 58,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 8,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 200,
            "Percentage_of_Occupancy_Total": 82.5,
            "Average_Daily_Census_Total": 165
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.201721, 42.188862]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "725 North Street",
            "TOWN": "Pittsfield",
            "ZIPCODE": 1201,
            "NAME": "Berkshire Medical Center - Berkshire Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 7,
            "DPHNUMBER": 2313,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 89,
            "Staffed_Beds_Pediatric": 2,
            "Staffed_Beds_Obstetric": 5,
            "Staffed_Beds_Psychiatric": 35,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 25,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 14,
            "Staffed_Beds_Total": 196,
            "Percentage_of_Occupancy_Total": 88.7,
            "Average_Daily_Census_Total": 173.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-73.249344, 42.459656]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "275 Sandwich Street",
            "TOWN": "Plymouth",
            "ZIPCODE": 2360,
            "NAME": "Jordan Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 79,
            "DPHNUMBER": 2082,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 104,
            "Staffed_Beds_Pediatric": 5,
            "Staffed_Beds_Obstetric": 12,
            "Staffed_Beds_Psychiatric": 19,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 13,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 172,
            "Percentage_of_Occupancy_Total": 68.4,
            "Average_Daily_Census_Total": 117.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.6452072, 41.9444885]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "114 Whitwell Street",
            "TOWN": "Quincy",
            "ZIPCODE": 2169,
            "NAME": "Quincy Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 112,
            "DPHNUMBER": 2151,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 61,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 12,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 93,
            "Percentage_of_Occupancy_Total": 77.2,
            "Average_Daily_Census_Total": 71.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.012978, 42.251953]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "81 Highland Avenue",
            "TOWN": "Salem",
            "ZIPCODE": 1970,
            "NAME": "North Shore Medical Center  - Salem Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "N",
            "ORG_ID": 116,
            "DPHNUMBER": 2014,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.90712, 42.510777]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "100 South Street",
            "TOWN": "Southbridge",
            "ZIPCODE": 1550,
            "NAME": "Harrington Memorial Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 68,
            "DPHNUMBER": 2143,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 72,
            "Staffed_Beds_Pediatric": 11,
            "Staffed_Beds_Obstetric": 11,
            "Staffed_Beds_Psychiatric": 14,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 126,
            "Percentage_of_Occupancy_Total": 38,
            "Average_Daily_Census_Total": 47.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.0418777, 42.0772411]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "759 Chestnut Street",
            "TOWN": "Springfield",
            "ZIPCODE": 1199,
            "NAME": "Baystate Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 4,
            "DPHNUMBER": 2339,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 435,
            "Staffed_Beds_Pediatric": 47,
            "Staffed_Beds_Obstetric": 64,
            "Staffed_Beds_Psychiatric": 28,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 33,
            "Staffed_Beds_CoronaryICU": 24,
            "Staffed_Beds_NeonatalICU": 55,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 749,
            "Percentage_of_Occupancy_Total": 65.8,
            "Average_Daily_Census_Total": 492.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.6050042, 42.1202899]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "271 Carew Street",
            "TOWN": "Springfield",
            "ZIPCODE": 1102,
            "NAME": "Mercy Medical Center - Springfield Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 119,
            "DPHNUMBER": 2149,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 156,
            "Staffed_Beds_Pediatric": 3,
            "Staffed_Beds_Obstetric": 16,
            "Staffed_Beds_Psychiatric": 74,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 16,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 60,
            "Staffed_Beds_Total": 420,
            "Percentage_of_Occupancy_Total": 57.5,
            "Average_Daily_Census_Total": 241.6
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.595428, 42.1157697]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "88 Washington Street",
            "TOWN": "Taunton",
            "ZIPCODE": 2780,
            "NAME": "Morton Hospital and Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 99,
            "DPHNUMBER": 2022,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 60,
            "Staffed_Beds_Pediatric": 3,
            "Staffed_Beds_Obstetric": 13,
            "Staffed_Beds_Psychiatric": 12,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 8,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 110,
            "Percentage_of_Occupancy_Total": 75,
            "Average_Daily_Census_Total": 82.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.0952225, 41.9063339]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "85 South Street",
            "TOWN": "Ware",
            "ZIPCODE": 1082,
            "NAME": "Baystate Mary Lane Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 6,
            "DPHNUMBER": 2148,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 16,
            "Staffed_Beds_Pediatric": 5,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 4,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 25,
            "Percentage_of_Occupancy_Total": 35.4,
            "Average_Daily_Census_Total": 8.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.2412577, 42.2534709]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "43 High Street",
            "TOWN": "Wareham",
            "ZIPCODE": 2571,
            "NAME": "Southcoast Hospitals Group - Tobey Hospital Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 145,
            "DPHNUMBER": 2106,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.7149876, 41.7560922]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "41 Highland Avenue",
            "TOWN": "Winchester",
            "ZIPCODE": 1890,
            "NAME": "Winchester Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 138,
            "DPHNUMBER": 2094,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 147,
            "Staffed_Beds_Pediatric": 12,
            "Staffed_Beds_Obstetric": 20,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 10,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 229,
            "Percentage_of_Occupancy_Total": 62.8,
            "Average_Daily_Census_Total": 143.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.122528, 42.465919]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "119 Belmont Street",
            "TOWN": "Worcester",
            "ZIPCODE": 1605,
            "NAME": "UMass Memorial Medical Center - Memorial Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 130,
            "DPHNUMBER": 2124,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.792244, 42.27285]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "55 Lake Avenue North",
            "TOWN": "Worcester",
            "ZIPCODE": 1655,
            "NAME": "UMass Memorial Medical Center - University Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 131,
            "DPHNUMBER": 2841,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Academic Medical Center",
            "Staffed_Beds_MedSurg": 374,
            "Staffed_Beds_Pediatric": 37,
            "Staffed_Beds_Obstetric": 65,
            "Staffed_Beds_Psychiatric": 53,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 81,
            "Staffed_Beds_CoronaryICU": 28,
            "Staffed_Beds_NeonatalICU": 27,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 734,
            "Percentage_of_Occupancy_Total": 79.8,
            "Average_Daily_Census_Total": 585.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.7590824, 42.2786448]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "27 Park Street",
            "TOWN": "Barnstable",
            "ZIPCODE": 2601,
            "NAME": "Cape Cod Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 39,
            "DPHNUMBER": 2135,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 197,
            "Staffed_Beds_Pediatric": 4,
            "Staffed_Beds_Obstetric": 14,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 11,
            "Staffed_Beds_CoronaryICU": 13,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 269,
            "Percentage_of_Occupancy_Total": 67.7,
            "Average_Daily_Census_Total": 182
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.273659, 41.653023]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "85 Herrick Street",
            "TOWN": "Beverly",
            "ZIPCODE": 1915,
            "NAME": "Northeast Hospital Corporation - Beverly Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "N",
            "ORG_ID": 110,
            "DPHNUMBER": 2007,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 219,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 31,
            "Staffed_Beds_Psychiatric": 92,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 22,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 12,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 404,
            "Percentage_of_Occupancy_Total": 63.2,
            "Average_Daily_Census_Total": 255.5
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.875427, 42.564068]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "363 Highland Avenue",
            "TOWN": "Fall River",
            "ZIPCODE": 2720,
            "NAME": "Southcoast Hospitals Group - Charlton Memorial Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 123,
            "DPHNUMBER": 2337,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.1467542, 41.7104027]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "795 Middle Street",
            "TOWN": "Fall River",
            "ZIPCODE": 2721,
            "NAME": "Saint Anne's Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 114,
            "DPHNUMBER": 2011,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 81,
            "Staffed_Beds_Pediatric": 10,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 16,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 113,
            "Percentage_of_Occupancy_Total": 84,
            "Average_Daily_Census_Total": 94.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.164856, 41.692223]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "29 Lewis Avenue",
            "TOWN": "Great Barrington",
            "ZIPCODE": 1230,
            "NAME": "Fairview Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 8,
            "DPHNUMBER": 2052,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 16,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 4,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 4,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 28,
            "Percentage_of_Occupancy_Total": 38.5,
            "Average_Daily_Census_Total": 10.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-73.3708861, 42.1920644]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "60 Hospital Road",
            "TOWN": "Leominster",
            "ZIPCODE": 1453,
            "NAME": "Health Alliance Hospital -- Leominster Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 8509,
            "DPHNUMBER": 2127,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.7614561, 42.5411466]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "575 Beech Street",
            "TOWN": "Holyoke",
            "ZIPCODE": 1040,
            "NAME": "Holyoke Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 77,
            "DPHNUMBER": 2145,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 140,
            "Staffed_Beds_Pediatric": 7,
            "Staffed_Beds_Obstetric": 13,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 12,
            "Staffed_Beds_CoronaryICU": 6,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 208,
            "Percentage_of_Occupancy_Total": 37.1,
            "Average_Daily_Census_Total": 77.1
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.627625, 42.200382]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "One General Street",
            "TOWN": "Lawrence",
            "ZIPCODE": 1842,
            "NAME": "Lawrence General Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "N",
            "ORG_ID": 83,
            "DPHNUMBER": 2099,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 120,
            "Staffed_Beds_Pediatric": 20,
            "Staffed_Beds_Obstetric": 30,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 9,
            "Staffed_Beds_CoronaryICU": 10,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 230,
            "Percentage_of_Occupancy_Total": 53.4,
            "Average_Daily_Census_Total": 122.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.14868, 42.7091273]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "92 Highland Street",
            "TOWN": "Milton",
            "ZIPCODE": 2186,
            "NAME": "Milton Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 98,
            "DPHNUMBER": 2227,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 65,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 7,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 72,
            "Percentage_of_Occupancy_Total": 70.3,
            "Average_Daily_Census_Total": 50.6
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.077156, 42.251331]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "57 Prospect Street",
            "TOWN": "Nantucket",
            "ZIPCODE": 2554,
            "NAME": "Nantucket Cottage Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 101,
            "DPHNUMBER": 2044,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 11,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 4,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 0,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 19,
            "Percentage_of_Occupancy_Total": 28.4,
            "Average_Daily_Census_Total": 5.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.101006, 41.275085]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "115 West Silver Street",
            "TOWN": "Westfield",
            "ZIPCODE": 1086,
            "NAME": "Noble Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 106,
            "DPHNUMBER": 2076,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 50,
            "Staffed_Beds_Pediatric": 6,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 15,
            "Staffed_Beds_Total": 97,
            "Percentage_of_Occupancy_Total": 53.2,
            "Average_Daily_Census_Total": 51.6
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.759209, 42.118069]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "71 Hospital Avenue",
            "TOWN": "North Adams",
            "ZIPCODE": 1247,
            "NAME": "North Adams Regional Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 107,
            "DPHNUMBER": 2061,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 58,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 11,
            "Staffed_Beds_Psychiatric": 20,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 16,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 117,
            "Percentage_of_Occupancy_Total": 23.7,
            "Average_Daily_Census_Total": 27.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-73.1095009, 42.7059435]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "55 Fogg Road",
            "TOWN": "Weymouth",
            "ZIPCODE": 2190,
            "NAME": "South Shore Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "N",
            "ORG_ID": 122,
            "DPHNUMBER": 2107,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 205,
            "Staffed_Beds_Pediatric": 17,
            "Staffed_Beds_Obstetric": 51,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 24,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 10,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 374,
            "Percentage_of_Occupancy_Total": 71.9,
            "Average_Daily_Census_Total": 268.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.954231, 42.175583]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "1493 Cambridge Street",
            "TOWN": "Cambridge",
            "ZIPCODE": 2139,
            "NAME": "Cambridge Health Alliance - Cambridge Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 27,
            "DPHNUMBER": 2108,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 106,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 14,
            "Staffed_Beds_Psychiatric": 62,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 12,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 234,
            "Percentage_of_Occupancy_Total": 72,
            "Average_Daily_Census_Total": 168.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.10438, 42.3742441]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "40 Wright Street",
            "TOWN": "Palmer",
            "ZIPCODE": 1069,
            "NAME": "Wing Memorial Hospital and Medical Centers",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 139,
            "DPHNUMBER": 2181,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 40,
            "Staffed_Beds_Pediatric": 4,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 24,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 74,
            "Percentage_of_Occupancy_Total": 64.7,
            "Average_Daily_Census_Total": 47.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.340591, 42.169632]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "1153 Centre Street",
            "TOWN": "Boston",
            "ZIPCODE": 2130,
            "NAME": "Faulkner Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 59,
            "DPHNUMBER": 2048,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 56,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 21,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 5,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 92,
            "Percentage_of_Occupancy_Total": 99.6,
            "Average_Daily_Census_Total": 91.6
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.1278245, 42.3002762]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "75 Francis Street",
            "TOWN": "Boston",
            "ZIPCODE": 2115,
            "NAME": "Brigham and Women's Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 22,
            "DPHNUMBER": 2921,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Academic Medical Center",
            "Staffed_Beds_MedSurg": 505,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 90,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 20,
            "Staffed_Beds_CoronaryICU": 10,
            "Staffed_Beds_NeonatalICU": 46,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 845,
            "Percentage_of_Occupancy_Total": 85.4,
            "Average_Daily_Census_Total": 721.6
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.1075349, 42.3359462]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "2100 Dorchester Avenue",
            "TOWN": "Boston",
            "ZIPCODE": 2124,
            "NAME": "Caritas Carney Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 42,
            "DPHNUMBER": 2003,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.065147, 42.27739]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "300 Longwood Avenue",
            "TOWN": "Boston",
            "ZIPCODE": 2115,
            "NAME": "Children's Hospital Boston",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 46,
            "DPHNUMBER": 2139,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Specialty Hospital",
            "Staffed_Beds_MedSurg": 0,
            "Staffed_Beds_Pediatric": 264,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 16,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 70,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 24,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 395,
            "Percentage_of_Occupancy_Total": 71.2,
            "Average_Daily_Census_Total": 281.1
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.10537, 42.336891]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "140 Lincoln Avenue",
            "TOWN": "Haverhill",
            "ZIPCODE": 1830,
            "NAME": "Merrimack Valley Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 70,
            "DPHNUMBER": 2131,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 50,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 17,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 8,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 75,
            "Percentage_of_Occupancy_Total": 62.7,
            "Average_Daily_Census_Total": 47.1
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.04525, 42.7625924]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "55 Fruit Street",
            "TOWN": "Boston",
            "ZIPCODE": 2114,
            "NAME": "Massachusetts General Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 91,
            "DPHNUMBER": 2168,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Academic Medical Center",
            "Staffed_Beds_MedSurg": 720,
            "Staffed_Beds_Pediatric": 44,
            "Staffed_Beds_Obstetric": 27,
            "Staffed_Beds_Psychiatric": 24,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 73,
            "Staffed_Beds_CoronaryICU": 34,
            "Staffed_Beds_NeonatalICU": 14,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 993,
            "Percentage_of_Occupancy_Total": 81.2,
            "Average_Daily_Census_Total": 805.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.0693745, 42.3624565]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "125 Parker Hill Avenue",
            "TOWN": "Boston",
            "ZIPCODE": 2120,
            "NAME": "New England Baptist Hospital",
            "STATE": "MA",
            "ER_STATUS": "N",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 103,
            "DPHNUMBER": 2059,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Specialty Hospital",
            "Staffed_Beds_MedSurg": 90,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 5,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 95,
            "Percentage_of_Occupancy_Total": 73.8,
            "Average_Daily_Census_Total": 70.1
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.106255, 42.329189]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "235 North Pearl Street",
            "TOWN": "Brockton",
            "ZIPCODE": 2301,
            "NAME": "Caritas Good Samaritan Medical Center - Brockton Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 62,
            "DPHNUMBER": 2101,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.0658326, 42.0978733]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "41 Mall Road",
            "TOWN": "Burlington",
            "ZIPCODE": 1805,
            "NAME": "Lahey Clinic Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 81,
            "DPHNUMBER": 2033,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 287,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 54,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 341,
            "Percentage_of_Occupancy_Total": 81.4,
            "Average_Daily_Census_Total": 277.6
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.204704, 42.484043]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "103 Garland Street",
            "TOWN": "Everett",
            "ZIPCODE": 2149,
            "NAME": "Cambridge Health Alliance - Whidden Memorial Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 142,
            "DPHNUMBER": 2046,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.039162, 42.409153]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "298 Washington Street",
            "TOWN": "Gloucester",
            "ZIPCODE": 1930,
            "NAME": "Northeast Hospital Corporation - Addison Gilbert Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 109,
            "DPHNUMBER": 2016,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.681366, 42.624805]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "295 Varnum Avenue",
            "TOWN": "Lowell",
            "ZIPCODE": 1854,
            "NAME": "Lowell General Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "N",
            "ORG_ID": 85,
            "DPHNUMBER": 2040,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 119,
            "Staffed_Beds_Pediatric": 20,
            "Staffed_Beds_Obstetric": 26,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 12,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 215,
            "Percentage_of_Occupancy_Total": 72.1,
            "Average_Daily_Census_Total": 155
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.3427405, 42.6461095]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "585 Lebanon Street",
            "TOWN": "Melrose",
            "ZIPCODE": 2176,
            "NAME": "Hallmark Health System - Melrose-Wakefield Hospital Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 141,
            "DPHNUMBER": 2058,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.0619246, 42.460172]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "14 Prospect Street",
            "TOWN": "Milford",
            "ZIPCODE": 1757,
            "NAME": "Milford Regional Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 97,
            "DPHNUMBER": 2105,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 87,
            "Staffed_Beds_Pediatric": 10,
            "Staffed_Beds_Obstetric": 14,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 10,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 136,
            "Percentage_of_Occupancy_Total": 63.2,
            "Average_Daily_Census_Total": 86
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.5291601, 42.1328983]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "123 Summer Street",
            "TOWN": "Worcester",
            "ZIPCODE": 1608,
            "NAME": "Saint Vincent Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "Y",
            "ORG_ID": 127,
            "DPHNUMBER": 2128,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Teaching Hospital",
            "Staffed_Beds_MedSurg": 201,
            "Staffed_Beds_Pediatric": 4,
            "Staffed_Beds_Obstetric": 28,
            "Staffed_Beds_Psychiatric": 15,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 22,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 301,
            "Percentage_of_Occupancy_Total": 67.7,
            "Average_Daily_Census_Total": 203.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.7955638, 42.266084]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "330 Brookline Avenue",
            "TOWN": "Boston",
            "ZIPCODE": 2215,
            "NAME": "Beth Israel Deaconess Medical Center - East Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 10,
            "DPHNUMBER": 2069,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Academic Medical Center",
            "Staffed_Beds_MedSurg": 309,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 48,
            "Staffed_Beds_Psychiatric": 22,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 54,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 9,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 499,
            "Percentage_of_Occupancy_Total": 100,
            "Average_Daily_Census_Total": 499
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.104889, 42.339725]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "133 Old Road to Nine Acre Corner",
            "TOWN": "Concord",
            "ZIPCODE": 1742,
            "NAME": "Emerson Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 57,
            "DPHNUMBER": 2018,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 70,
            "Staffed_Beds_Pediatric": 11,
            "Staffed_Beds_Obstetric": 24,
            "Staffed_Beds_Psychiatric": 29,
            "Staffed_Beds_SNF": 20,
            "Staffed_Beds_MedSurgICU": 14,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 5,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 197,
            "Percentage_of_Occupancy_Total": 59.1,
            "Average_Daily_Census_Total": 116.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.375, 42.45182]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "One Hospital Road",
            "TOWN": "Oak Bluffs",
            "ZIPCODE": 2557,
            "NAME": "Martha's Vineyard Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 88,
            "DPHNUMBER": 2042,
            "EMSREGION": 5,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 12,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 4,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 3,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 25,
            "Percentage_of_Occupancy_Total": 59,
            "Average_Daily_Census_Total": 14.8
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-70.5806518, 41.460905]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "One Hospital Drive",
            "TOWN": "Lowell",
            "ZIPCODE": 1852,
            "NAME": "Saints Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 115,
            "DPHNUMBER": 2063,
            "EMSREGION": 3,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 87,
            "Staffed_Beds_Pediatric": 4,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 9,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 100,
            "Percentage_of_Occupancy_Total": 66,
            "Average_Daily_Census_Total": 66
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.3004099, 42.6453625]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "157 Union Street",
            "TOWN": "Marlborough",
            "ZIPCODE": 1752,
            "NAME": "Marlborough Hospital",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 133,
            "DPHNUMBER": 2103,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community Hospital",
            "Staffed_Beds_MedSurg": 35,
            "Staffed_Beds_Pediatric": 0,
            "Staffed_Beds_Obstetric": 0,
            "Staffed_Beds_Psychiatric": 22,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 10,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 67,
            "Percentage_of_Occupancy_Total": 74.2,
            "Average_Daily_Census_Total": 49.7
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.5537284, 42.3544266]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "800 Washington Street",
            "TOWN": "Boston",
            "ZIPCODE": 2111,
            "NAME": "Tufts Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 104,
            "DPHNUMBER": 2299,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Academic Medical Center",
            "Staffed_Beds_MedSurg": 145,
            "Staffed_Beds_Pediatric": 21,
            "Staffed_Beds_Obstetric": 21,
            "Staffed_Beds_Psychiatric": 18,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 39,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 32,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 292,
            "Percentage_of_Occupancy_Total": 94.8,
            "Average_Daily_Census_Total": 276.9
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.063309, 42.34951]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "818 Harrison Avenue",
            "TOWN": "Boston",
            "ZIPCODE": 2118,
            "NAME": "Boston Medical Center - Menino Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "Y",
            "TEACHING": "Y",
            "ORG_ID": 16,
            "DPHNUMBER": 2307,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Academic Medical Center",
            "Staffed_Beds_MedSurg": 306,
            "Staffed_Beds_Pediatric": 36,
            "Staffed_Beds_Obstetric": 39,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 58,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 15,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 504,
            "Percentage_of_Occupancy_Total": 65.3,
            "Average_Daily_Census_Total": 329
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.0737894, 42.3359368]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "275 Nichols Road",
            "TOWN": "Fitchburg",
            "ZIPCODE": 1420,
            "NAME": "Health Alliance Hospital -- Burbank Campus",
            "STATE": "MA",
            "ER_STATUS": "N",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 8548,
            "DPHNUMBER": 2034,
            "EMSREGION": 2,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 61,
            "Staffed_Beds_Pediatric": 3,
            "Staffed_Beds_Obstetric": 7,
            "Staffed_Beds_Psychiatric": 0,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 8,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 86,
            "Percentage_of_Occupancy_Total": 92.3,
            "Average_Daily_Census_Total": 79.4
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.806419, 42.597851]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "1233 Main Street",
            "TOWN": "Holyoke",
            "ZIPCODE": 1040,
            "NAME": "Mercy Medical Center - Providence Behavioral Health Hospital Campus",
            "STATE": "MA",
            "ER_STATUS": "N",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 118,
            "DPHNUMBER": 2150,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.635574, 42.165344]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "67 Union Street",
            "TOWN": "Natick",
            "ZIPCODE": 1760,
            "NAME": "MetroWest Medical Center - Leonard Morse Campus",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 457,
            "DPHNUMBER": 2039,
            "EMSREGION": 4,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.335495, 42.280228]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "164 High Street",
            "TOWN": "Greenfield",
            "ZIPCODE": 1301,
            "NAME": "Baystate Franklin Medical Center",
            "STATE": "MA",
            "ER_STATUS": "Y",
            "TRAUMA": "N",
            "TEACHING": "N",
            "ORG_ID": 5,
            "DPHNUMBER": 2120,
            "EMSREGION": 1,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "Community, Disproportionate Share Hospital",
            "Staffed_Beds_MedSurg": 44,
            "Staffed_Beds_Pediatric": 3,
            "Staffed_Beds_Obstetric": 15,
            "Staffed_Beds_Psychiatric": 22,
            "Staffed_Beds_SNF": 0,
            "Staffed_Beds_MedSurgICU": 6,
            "Staffed_Beds_CoronaryICU": 0,
            "Staffed_Beds_NeonatalICU": 0,
            "Staffed_Beds_Chronic_Rehab": 0,
            "Staffed_Beds_Total": 110,
            "Percentage_of_Occupancy_Total": 48.7,
            "Average_Daily_Census_Total": 53.5
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-72.592545, 42.59584]
        }
    }, {
        "type": "Feature",
        "properties": {
            "ADDRESS": "71 Walnut St",
            "TOWN": "Foxboro",
            "ZIPCODE": 2035,
            "NAME": "Caritas Good Samaritan Medical Center - NORCAP Lodge Campus",
            "STATE": "MA",
            "ER_STATUS": "",
            "TRAUMA": "",
            "TEACHING": "",
            "ORG_ID": 0,
            "DPHNUMBER": "",
            "EMSREGION": 0,
            "marker-color": "#009933",
            "marker-size": "large",
            "marker-symbol": "hospital",
            "Hospital_Type": "No Data Available",
            "Staffed_Beds_MedSurg": "No Data Available",
            "Staffed_Beds_Pediatric": "No Data Available",
            "Staffed_Beds_Obstetric": "No Data Available",
            "Staffed_Beds_Psychiatric": "No Data Available",
            "Staffed_Beds_SNF": "No Data Available",
            "Staffed_Beds_MedSurgICU": "No Data Available",
            "Staffed_Beds_CoronaryICU": "No Data Available",
            "Staffed_Beds_NeonatalICU": "No Data Available",
            "Staffed_Beds_Chronic_Rehab": "No Data Available",
            "Staffed_Beds_Total": "No Data Available",
            "Percentage_of_Occupancy_Total": "No Data Available",
            "Average_Daily_Census_Total": "No Data Available"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [-71.2408829, 42.0497055]
        }
    }]
};